name: BuycraftBedrock
main: net.buycraft.plugin.bedrock.bukkit.BuycraftPlugin
version: ${project.version}
author: Buycraft
api-version: "1.13"
depend: ["floodgate-bukkit"]
commands:
  bedrocktebex:
    aliases: [bedrockcraft]
    description: Main command for the Tebex plugin.